export const columns = [
  { id: "reference", label: "Kayıt No.", minWidth: 170 },
  { id: "step", label: "Sıra No.", minWidth: 170 },
  {
    id: "charge",
    label: "Şarj No.",
    minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "piece",
    label: "Adet",
    minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "piece_kg",
    label: "Adet Kg.",
    minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "total_kg",
    label: "Toplam Kg.",
    minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "prepared",
    label: "Dolduran",
    minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "options",
    label: "Düzenle",
    minWidth: 170,
    align: "right",
  },
];
